<a href="https://colab.research.google.com/github/kingketan9/BigDataLabs/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null ### Installing Java

In [ ]:
!wget -q http://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz #### Installing Spark and Hadoop on the worker node
!tar xf spark-3.1.1-bin-hadoop3.2.tgz
!pip install -q findspark

In [ ]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.1-bin-hadoop3.2"

import findspark
findspark.init()
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()
spark.conf.set("spark.sql.repl.eagerEval.enabled", True) # Property used to format output tables better
spark #### Creating a Sparksession

Create the following dataframe

 df1 = spark.createDataFrame([(1, 144.5, 5.9, 33, 'M'),(2, 167.2, 5.4, 45, 'M'),(3, 124.1, 5.2, 23, 'F'),(4, 140.4, 5.2, 34, 'M'),(5, 133.2, 5.7, 54, 'F'),(6, 114.1, 4.8, 23, 'F'),
(7, 129.2, 5.3, 2, 'M'),], ['id', 'weight', 'height', 'age', 'gender'])

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, IntegerType, DoubleType, StringType

spark = SparkSession.builder.appName("CreateDataFrame").getOrCreate()

schema = StructType([
    StructField("id", IntegerType(), True),
    StructField("weight", DoubleType(), True),
    StructField("height", DoubleType(), True),
    StructField("age", IntegerType(), True),
    StructField("gender", StringType(), True)
])

data = [
    (1, 144.5, 5.9, 33, 'M'),
    (2, 167.2, 5.4, 45, 'M'),
    (3, 124.1, 5.2, 23, 'F'),
    (4, 140.4, 5.2, 34, 'M'),
    (5, 133.2, 5.7, 54, 'F'),
    (6, 114.1, 4.8, 23, 'F'),
    (7, 129.2, 5.3, 2, 'M')
]

df1 = spark.createDataFrame(data, schema=schema)

df1.show()


+---+------+------+---+------+
| id|weight|height|age|gender|
+---+------+------+---+------+
|  1| 144.5|   5.9| 33|     M|
|  2| 167.2|   5.4| 45|     M|
|  3| 124.1|   5.2| 23|     F|
|  4| 140.4|   5.2| 34|     M|
|  5| 133.2|   5.7| 54|     F|
|  6| 114.1|   4.8| 23|     F|
|  7| 129.2|   5.3|  2|     M|
+---+------+------+---+------+



 Create another dataframe


 df2 = spark.createDataFrame([(3, 'HR', 2500),(4, 'HR', 2700),(2, 'Marketing', 1300),(5, 'Marketing', 1900),(1, 'Technical', 2100),(7, 'Technical', 2500),(8, 'Admin', 2600),
 ], ['id', 'Department', 'salary'])

In [ ]:
schema2 = StructType([
    StructField("id", IntegerType(), True),
    StructField("Department", StringType(), True),
    StructField("salary", IntegerType(), True)
])

data2 = [
    (3, 'HR', 2500),
    (4, 'HR', 2700),
    (2, 'Marketing', 1300),
    (5, 'Marketing', 1900),
    (1, 'Technical', 2100),
    (7, 'Technical', 2500),
    (8, 'Admin', 2600)
]

df2 = spark.createDataFrame(data2, schema=schema2)

df2.show()

+---+----------+------+
| id|Department|salary|
+---+----------+------+
|  3|        HR|  2500|
|  4|        HR|  2700|
|  2| Marketing|  1300|
|  5| Marketing|  1900|
|  1| Technical|  2100|
|  7| Technical|  2500|
|  8|     Admin|  2600|
+---+----------+------+



Perform various join operations on these two dataframes. Also explain what the join operations do.

In [ ]:
inner_join = df1.join(df2, on=['id'], how='inner')

left_join = df1.join(df2, on=['id'], how='left')

right_join = df1.join(df2, on=['id'], how='right')

outer_join = df1.join(df2, on=['id'], how='outer')

Perform an inner join of these two dataframes.

In [ ]:
inner_join.show()

+---+------+------+---+------+----------+------+
| id|weight|height|age|gender|Department|salary|
+---+------+------+---+------+----------+------+
|  1| 144.5|   5.9| 33|     M| Technical|  2100|
|  3| 124.1|   5.2| 23|     F|        HR|  2500|
|  5| 133.2|   5.7| 54|     F| Marketing|  1900|
|  4| 140.4|   5.2| 34|     M|        HR|  2700|
|  7| 129.2|   5.3|  2|     M| Technical|  2500|
|  2| 167.2|   5.4| 45|     M| Marketing|  1300|
+---+------+------+---+------+----------+------+



Perform an outer join of these two dataframes.

In [ ]:
outer_join.show()

+---+------+------+----+------+----------+------+
| id|weight|height| age|gender|Department|salary|
+---+------+------+----+------+----------+------+
|  1| 144.5|   5.9|  33|     M| Technical|  2100|
|  6| 114.1|   4.8|  23|     F|      null|  null|
|  3| 124.1|   5.2|  23|     F|        HR|  2500|
|  5| 133.2|   5.7|  54|     F| Marketing|  1900|
|  4| 140.4|   5.2|  34|     M|        HR|  2700|
|  8|  null|  null|null|  null|     Admin|  2600|
|  7| 129.2|   5.3|   2|     M| Technical|  2500|
|  2| 167.2|   5.4|  45|     M| Marketing|  1300|
+---+------+------+----+------+----------+------+



Perform a leftouter join of these two dataframes.

In [ ]:
left_join.show()

+---+------+------+---+------+----------+------+
| id|weight|height|age|gender|Department|salary|
+---+------+------+---+------+----------+------+
|  1| 144.5|   5.9| 33|     M| Technical|  2100|
|  6| 114.1|   4.8| 23|     F|      null|  null|
|  3| 124.1|   5.2| 23|     F|        HR|  2500|
|  5| 133.2|   5.7| 54|     F| Marketing|  1900|
|  4| 140.4|   5.2| 34|     M|        HR|  2700|
|  7| 129.2|   5.3|  2|     M| Technical|  2500|
|  2| 167.2|   5.4| 45|     M| Marketing|  1300|
+---+------+------+---+------+----------+------+



Perform a rightouter join of these two dataframes.

In [ ]:
right_join.show()

+---+------+------+----+------+----------+------+
| id|weight|height| age|gender|Department|salary|
+---+------+------+----+------+----------+------+
|  1| 144.5|   5.9|  33|     M| Technical|  2100|
|  3| 124.1|   5.2|  23|     F|        HR|  2500|
|  5| 133.2|   5.7|  54|     F| Marketing|  1900|
|  4| 140.4|   5.2|  34|     M|        HR|  2700|
|  8|  null|  null|null|  null|     Admin|  2600|
|  7| 129.2|   5.3|   2|     M| Technical|  2500|
|  2| 167.2|   5.4|  45|     M| Marketing|  1300|
+---+------+------+----+------+----------+------+



Perform a leftsemi join of these two dataframes.


In [ ]:
left_semi_join = df1.join(df2, on=['id'], how='left_semi')

left_semi_join.show()

+---+------+------+---+------+
| id|weight|height|age|gender|
+---+------+------+---+------+
|  1| 144.5|   5.9| 33|     M|
|  3| 124.1|   5.2| 23|     F|
|  5| 133.2|   5.7| 54|     F|
|  4| 140.4|   5.2| 34|     M|
|  7| 129.2|   5.3|  2|     M|
|  2| 167.2|   5.4| 45|     M|
+---+------+------+---+------+



Perform a leftanti join of these two dataframes.

In [ ]:
left_anti_join = df1.join(df2, on=['id'], how='left_anti')

left_anti_join.show()

+---+------+------+---+------+
| id|weight|height|age|gender|
+---+------+------+---+------+
|  6| 114.1|   4.8| 23|     F|
+---+------+------+---+------+



 Create the dataframe


df = spark.createDataFrame([(1, 144.5, 5.9, 33, 'M'),(2, 167.2, 5.4, 45, 'M'),(3, 124.1, 5.2, 23, 'F'),(4, 144.5, 5.9, 33, 'M'),(5, 133.2, 5.7, 54, 'F'),(3, 124.1, 5.2, 23, 'F'),
(5, 129.2, 5.3, 42, 'M'),], ['id', 'weight', 'height', 'age', 'gender'])

In [ ]:
schema3 = StructType([
    StructField("id", IntegerType(), True),
    StructField("weight", DoubleType(), True),
    StructField("height", DoubleType(), True),
    StructField("age", IntegerType(), True),
    StructField("gender", StringType(), True)
])

data3 = [
    (1, 144.5, 5.9, 33, 'M'),
    (2, 167.2, 5.4, 45, 'M'),
    (3, 124.1, 5.2, 23, 'F'),
    (4, 144.5, 5.9, 33, 'M'),
    (5, 133.2, 5.7, 54, 'F'),
    (3, 124.1, 5.2, 23, 'F'),
    (5, 129.2, 5.3, 42, 'M')
]

df3 = spark.createDataFrame(data3, schema=schema3)

df3.show()

+---+------+------+---+------+
| id|weight|height|age|gender|
+---+------+------+---+------+
|  1| 144.5|   5.9| 33|     M|
|  2| 167.2|   5.4| 45|     M|
|  3| 124.1|   5.2| 23|     F|
|  4| 144.5|   5.9| 33|     M|
|  5| 133.2|   5.7| 54|     F|
|  3| 124.1|   5.2| 23|     F|
|  5| 129.2|   5.3| 42|     M|
+---+------+------+---+------+



Drop duplicate rows

In [ ]:
df3_no_duplicates = df3.dropDuplicates()

df3_no_duplicates.show()

+---+------+------+---+------+
| id|weight|height|age|gender|
+---+------+------+---+------+
|  1| 144.5|   5.9| 33|     M|
|  5| 133.2|   5.7| 54|     F|
|  5| 129.2|   5.3| 42|     M|
|  3| 124.1|   5.2| 23|     F|
|  4| 144.5|   5.9| 33|     M|
|  2| 167.2|   5.4| 45|     M|
+---+------+------+---+------+



Drop rows which have the same data but different IDs

In [ ]:
df3_no_duplicate = df3.dropDuplicates(subset=[col for col in df3.columns if col != 'id'])

df3_no_duplicate.show()

+---+------+------+---+------+
| id|weight|height|age|gender|
+---+------+------+---+------+
|  2| 167.2|   5.4| 45|     M|
|  5| 133.2|   5.7| 54|     F|
|  1| 144.5|   5.9| 33|     M|
|  5| 129.2|   5.3| 42|     M|
|  3| 124.1|   5.2| 23|     F|
+---+------+------+---+------+



If two rows have the same ID but different data create a column of new IDs for each person

In [ ]:
from pyspark.sql.functions import monotonically_increasing_id

df3_with_unique_ids = df3.withColumn("new_id", monotonically_increasing_id())

df3_with_unique_ids.show()

+---+------+------+---+------+----------+
| id|weight|height|age|gender|    new_id|
+---+------+------+---+------+----------+
|  1| 144.5|   5.9| 33|     M|         0|
|  2| 167.2|   5.4| 45|     M|         1|
|  3| 124.1|   5.2| 23|     F|         2|
|  4| 144.5|   5.9| 33|     M|8589934592|
|  5| 133.2|   5.7| 54|     F|8589934593|
|  3| 124.1|   5.2| 23|     F|8589934594|
|  5| 129.2|   5.3| 42|     M|8589934595|
+---+------+------+---+------+----------+



 Create the following dataframe


 df_miss = spark.createDataFrame([(1, 143.5, 5.6, 28, 'M', 100000),(2, 167.2, 5.4, 45, 'M', None),(3, None , 5.2, None, None, None),(4, 144.5, 5.9, 33, 'M', None),(5, 133.2, 5.7, 54, 'F', None),
 (6, 124.1, 5.2, None, 'F', None),(7, 129.2, 5.3, 42, 'M', 76000),], ['id', 'weight', 'height', 'age', 'gender', 'income'])

In [ ]:
schema_miss = StructType([
    StructField("id", IntegerType(), True),
    StructField("weight", DoubleType(), True),
    StructField("height", DoubleType(), True),
    StructField("age", IntegerType(), True),
    StructField("gender", StringType(), True),
    StructField("income", IntegerType(), True)
])

data_miss = [
    (1, 143.5, 5.6, 28, 'M', 100000),
    (2, 167.2, 5.4, 45, 'M', None),
    (3, None, 5.2, None, None, None),
    (4, 144.5, 5.9, 33, 'M', None),
    (5, 133.2, 5.7, 54, 'F', None),
    (6, 124.1, 5.2, None, 'F', None),
    (7, 129.2, 5.3, 42, 'M', 76000)
]

df_miss = spark.createDataFrame(data_miss, schema=schema_miss)

df_miss.show()

+---+------+------+----+------+------+
| id|weight|height| age|gender|income|
+---+------+------+----+------+------+
|  1| 143.5|   5.6|  28|     M|100000|
|  2| 167.2|   5.4|  45|     M|  null|
|  3|  null|   5.2|null|  null|  null|
|  4| 144.5|   5.9|  33|     M|  null|
|  5| 133.2|   5.7|  54|     F|  null|
|  6| 124.1|   5.2|null|     F|  null|
|  7| 129.2|   5.3|  42|     M| 76000|
+---+------+------+----+------+------+



replace missing values with maen of each column

In [ ]:
from pyspark.sql.functions import mean, when, col

mean_values = df_miss.select([
    mean(when(col(column).isNotNull(), col(column))).alias(column)
    for column in df_miss.columns
])

def fill_with_mean(df, mean_values):
    for column in df.columns:
        mean_value = mean_values.first()[column]
        df = df.withColumn(column, when(df[column].isNull(), mean_value).otherwise(df[column]))
    return df

df_miss_filled = fill_with_mean(df_miss, mean_values)

df_miss_filled.show()

+---+------------------+------+----+------+--------+
| id|            weight|height| age|gender|  income|
+---+------------------+------+----+------+--------+
|1.0|             143.5|   5.6|28.0|     M|100000.0|
|2.0|             167.2|   5.4|45.0|     M| 88000.0|
|3.0|140.28333333333333|   5.2|40.0|  null| 88000.0|
|4.0|             144.5|   5.9|33.0|     M| 88000.0|
|5.0|             133.2|   5.7|54.0|     F| 88000.0|
|6.0|             124.1|   5.2|40.0|     F| 88000.0|
|7.0|             129.2|   5.3|42.0|     M| 76000.0|
+---+------------------+------+----+------+--------+



Consider the following dataframe:


 df_outliers = spark.createDataFrame([(1, 143.5, 5.3, 28),(2, 154.2, 5.5, 45),(3, 342.3, 5.1, 99),(4, 144.5, 5.5, 33),(5, 133.2, 5.4, 54),(6, 124.1, 5.1, 21),(7, 129.2, 5.3, 42),], ['id', 'weight', 'height', 'age'])

In [ ]:
from pyspark.sql.functions import stddev, mean, col
import pyspark.sql.functions as F

spark = SparkSession.builder.appName("Outliers").getOrCreate()

schema_outliers = StructType([
    StructField("id", IntegerType(), True),
    StructField("weight", DoubleType(), True),
    StructField("height", DoubleType(), True),
    StructField("age", IntegerType(), True)
])

data_outliers = [
    (1, 143.5, 5.3, 28),
    (2, 154.2, 5.5, 45),
    (3, 342.3, 5.1, 99),
    (4, 144.5, 5.5, 33),
    (5, 133.2, 5.4, 54),
    (6, 124.1, 5.1, 21),
    (7, 129.2, 5.3, 42)
]

Point out the outliers in the above dataframe

In [ ]:
df_outliers = spark.createDataFrame(data_outliers, schema=schema_outliers)

mean_weight = df_outliers.select(mean(col('weight'))).collect()[0][0]
stddev_weight = df_outliers.select(stddev(col('weight'))).collect()[0][0]

mean_height = df_outliers.select(mean(col('height'))).collect()[0][0]
stddev_height = df_outliers.select(stddev(col('height'))).collect()[0][0]

mean_age = df_outliers.select(mean(col('age'))).collect()[0][0]
stddev_age = df_outliers.select(stddev(col('age'))).collect()[0][0]

df_outliers = df_outliers.withColumn('weight_zscore', (col('weight') - mean_weight) / stddev_weight)
df_outliers = df_outliers.withColumn('height_zscore', (col('height') - mean_height) / stddev_height)
df_outliers = df_outliers.withColumn('age_zscore', (col('age') - mean_age) / stddev_age)

z_score_threshold = 2000

outliers = df_outliers.filter(
    (F.abs(col('weight_zscore')) > z_score_threshold) |
    (F.abs(col('height_zscore')) > z_score_threshold) |
    (F.abs(col('age_zscore')) > z_score_threshold)
)

outliers.show()

+---+------+------+---+-------------+-------------+----------+
| id|weight|height|age|weight_zscore|height_zscore|age_zscore|
+---+------+------+---+-------------+-------------+----------+
+---+------+------+---+-------------+-------------+----------+

